### ISSUE TITLE
Column scrolling down

### ISSUE THREAD

**Issue by cesards** [devspace/devspace-user-requests#84] opened 2016-03-15 21:05 UTC
A column doesn't support down scrolling, so I can barely see what's going on!

Thank you for your work, by the way!

**Comment by zenorocha** [comment] 2016-03-15 21:07
Hey @cesards, could you provide more info like a screenshot or something? I haven't seen other users with this kind of error yet.

**Comment by zenorocha** [comment] 2016-03-16 17:06
Closing since it wasn't able to reproduce.

**Closed as completed by zenorocha** 2016-03-16 17:06 UTC

**Comment by cesards** [comment] 2016-03-16 18:04
Sure!! Here you are :)   @zenorocha 

https://youtu.be/JQtGn946MFw

PS: You closed this too fast man!

**Comment by zenorocha** [comment] 2016-03-16 18:17
Ohhhh, so you're trying to say that you want #3
